title: EUROFEVER DETAILING
email: eurofeverdetailing@gmail.com
description: >-   
  Eurofever Detailing is an owner-operated automotive detailing studio based in South Austin, 
  specializing in long-term vehicle care, maintenance, and preservation. 
  From daily drivers to enthusiast-owned cars, every service is designed with transparency, 
  consistency, and attention to detail.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: eurofeverdetailing
youtube_username: eurofeverdetail
facebook_link: https://www.facebook.com/people/EuroFever-Detailing/61586192799708/
booking_link: https://book.squareup.com/appointments/tbmbrriui9zuy6/location/LMFW4DYGFWTWJ/services
deposit_amt: 50
days: Mon · Tue · Thu · Fri · Sat
hours: 8:00am–6:00pm
location: https://maps.app.goo.gl/nbLzkF1amdqP8nKX7
phone: 5123487242
header_pages:
  - pages/about.md
  - pages/services.md
  - pages/policies-faqs.md
  - pages/gallery.md
  - pages/testimonials.md
  - pages/contact.md
  - pages/blog.md

palette:
  carbon: "#050505"
  anthracite: "#59677B"

sass:
  sass_dir: _sass
  style: compressed

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - scripts/
